services:
  - type: web
    name: omniroute-service
    env: docker
    region: ohio
    plan: starter
    healthCheckPath: /v1/models
    envVars:
      - key: PORT
        value: 20128
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    disk:
      name: omniroute-data
      mountPath: /app/data
      sizeGB: 1
