'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'ja';

const dictionaries: Record<Language, Record<string, string>> = {
  en: {
    brandName: "Curricula.AI",
    dashboard: "Dashboard",
    syllabus: "Syllabus",
    learningStats: "Learning Stats",
    streak: "Learning Streak",
    activeDays: "Active Days",
    avatar: "Select Avatar",
    language: "Interface Language",
    logout: "Logout",
    settings: "Settings",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    searchPlaceholder: "Search concepts, lessons, summaries, or document meaning...",
    backToDashboard: "Back to Dashboard",
    courseSyllabus: "Course Syllabus",
    aiTutor: "AI Tutor",
    resumeLearning: "Resume Learning",
    exportCourse: "Export Course",
    chapter: "Chapter",
    lesson: "Lesson",
    startQuiz: "Start Quiz",
    suggestedQueries: "Suggested Queries",
    noCourses: "No courses generated yet. Upload a PDF below to get started!",
    uploadPdf: "Upload PDF",
    uploadSuccess: "Upload successful!",
    generatingCourse: "Generating Course...",
    createCourse: "Create Course",
    yourCourses: "Your Courses",
    studyStats: "Study Stats",
    recentActivity: "Recent Activity",
    settingsTitle: "Settings & Preferences",
    profile: "Profile Settings",
    security: "Security & 2FA",
    password: "Password Settings",
    notifications: "Notification Preferences",
    aiPreferences: "AI Model Preferences",
    appearance: "Theme & Appearance",
    account: "Account Management",
    signIn: "Sign In",
    signUp: "Sign Up",
    emailAddress: "Email Address",
    passwordLabel: "Password",
    forgotPassword: "Forgot Password?",
    firstName: "First Name",
    lastName: "Last Name",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    interactiveDiagrams: "Interactive Diagrams",
    visualMindMaps: "AI Visual Mind Maps & Diagrams",
    chapterTopic: "Chapter Topic",
    visualLayout: "Visual Layout Type",
    mindmap: "Mind Map",
    conceptFlowchart: "Concept Flowchart",
    sequenceDiagram: "Sequence Diagram",
    classStructure: "Class Structure",
    erd: "Entity Relationship (ERD)",
    exportSvg: "Export SVG",
    zoomControls: "Zoom Controls",
    fitToScreen: "Fit to Screen",
    regenerateDiagram: "Regenerate Diagram",
    chatCompanion: "AI Study Companion",
    documents: "Documents",
    courses: "Courses",
    completions: "Completions",
    avgQuizGrade: "Avg Quiz Grade",
    weeklyHours: "Weekly Study Hours",
    earnedBadges: "Earned Badges",
    library: "Library",
    noPdfs: "No PDFs uploaded yet.",
    search: "Search",
    days: "days"
  },
  es: {
    brandName: "Curricula.AI",
    dashboard: "Panel",
    syllabus: "Programa",
    learningStats: "Estadísticas de Aprendizaje",
    streak: "Racha de Aprendizaje",
    activeDays: "Días Activos",
    avatar: "Seleccionar Avatar",
    language: "Idioma de la Interfaz",
    logout: "Cerrar sesión",
    settings: "Configuración",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    searchPlaceholder: "Buscar conceptos, lecciones, resúmenes...",
    backToDashboard: "Volver al Panel",
    courseSyllabus: "Plan de Estudios del Curso",
    aiTutor: "Tutor IA",
    resumeLearning: "Reanudar Aprendizaje",
    exportCourse: "Exportar Curso",
    chapter: "Capítulo",
    lesson: "Lección",
    startQuiz: "Iniciar Cuestionario",
    suggestedQueries: "Consultas Sugeridas",
    noCourses: "Aún no se han generado cursos. ¡Sube un PDF abajo para comenzar!",
    uploadPdf: "Subir PDF",
    uploadSuccess: "¡Subida exitosa!",
    generatingCourse: "Generando Curso...",
    createCourse: "Crear Curso",
    yourCourses: "Tus Cursos",
    studyStats: "Estadísticas de Estudio",
    recentActivity: "Actividad Reciente",
    settingsTitle: "Configuración y Preferencias",
    profile: "Configuración de Perfil",
    security: "Seguridad y 2FA",
    password: "Configuración de Contraseña",
    notifications: "Preferencias de Notificación",
    aiPreferences: "Preferencias del Modelo IA",
    appearance: "Tema y Apariencia",
    account: "Gestión de Cuenta",
    signIn: "Iniciar Sesión",
    signUp: "Registrarse",
    emailAddress: "Correo Electrónico",
    passwordLabel: "Contraseña",
    forgotPassword: "¿Olviló su contraseña?",
    firstName: "Nombre",
    lastName: "Apellido",
    haveAccount: "¿Ya tiene una cuenta?",
    noAccount: "¿No tiene una cuenta?",
    interactiveDiagrams: "Diagramas Interactivos",
    visualMindMaps: "Mapas Mentales y Diagramas IA",
    chapterTopic: "Tema del Capítulo",
    visualLayout: "Tipo de Diseñó Visual",
    mindmap: "Mapa Mental",
    conceptFlowchart: "Diagrama de Flujo de Conceptos",
    sequenceDiagram: "Diagrama de Secuencia",
    classStructure: "Estructura de Clases",
    erd: "Relación de Entidades (ERD)",
    exportSvg: "Exportar SVG",
    zoomControls: "Controles de Zoom",
    fitToScreen: "Ajustar a la Pantalla",
    regenerateDiagram: "Regenerar Diagrama",
    chatCompanion: "Compañero de Estudio IA"
  },
  hi: {
    brandName: "Curricula.AI",
    dashboard: "डैशबोर्ड",
    syllabus: "पाठ्यक्रम",
    learningStats: "सीखने के आँकड़े",
    streak: "सीखने का क्रम",
    activeDays: "सक्रिय दिन",
    avatar: "अवतार चुनें",
    language: "इंटरफ़ेस भाषा",
    logout: "लॉगआउट",
    settings: "सेटिंग्स",
    saveChanges: "बदलाव सहेजें",
    cancel: "रद्द करें",
    searchPlaceholder: "सिद्धांत, पाठ, सारांश खोजें...",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    courseSyllabus: "कोर्स पाठ्यक्रम",
    aiTutor: "एआई ट्यूटर",
    resumeLearning: "सीखना फिर से शुरू करें",
    exportCourse: "कोर्स निर्यात करें",
    chapter: "अध्याय",
    lesson: "पाठ",
    startQuiz: "क्विज शुरू करें",
    suggestedQueries: "सुझाए गए प्रश्न",
    noCourses: "अभी तक कोई कोर्स नहीं बनाया गया है। शुरू करने के लिए नीचे पीडीएफ अपलोड करें!",
    uploadPdf: "पीडीएफ अपलोड करें",
    uploadSuccess: "अपलोड सफल!",
    generatingCourse: "कोर्स उत्पन्न हो रहा है...",
    createCourse: "कोर्स बनाएं",
    yourCourses: "आपके कोर्सेज",
    studyStats: "अध्ययन आँकड़े",
    recentActivity: "हाल की गतिविधि",
    settingsTitle: "सेटिंग्स और प्राथमिकताएं",
    profile: "प्रोफ़ाइल सेटिंग्स",
    security: "सुरक्षा और 2FA",
    password: "पासवर्ड सेटिंग्स",
    notifications: "अधिसूचना प्राथमिकताएं",
    aiPreferences: "एआई मॉडल प्राथमिकताएं",
    appearance: "थीम और स्वरूप",
    account: "खाता प्रबंधन",
    signIn: "साइन इन",
    signUp: "साइन अप",
    emailAddress: "ईमेल पता",
    passwordLabel: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    haveAccount: "क्या आपके पास पहले से खाता है?",
    noAccount: "खाता नहीं है?",
    interactiveDiagrams: "इंटरएक्टिव चित्र",
    visualMindMaps: "एआई विजुअल माइंड मैप्स और चित्र",
    chapterTopic: "अध्याय विषय",
    visualLayout: "दृश्य लेआउट प्रकार",
    mindmap: "माइंड मैप",
    conceptFlowchart: "सिद्धांत फ्लोचार्ट",
    sequenceDiagram: "अनुक्रम आरेख",
    classStructure: "क्लास संरचना",
    erd: "इकाई संबंध आरेख (ERD)",
    exportSvg: "एसवीजी निर्यात करें",
    zoomControls: "ज़ूम नियंत्रण",
    fitToScreen: "स्क्रीन में फिट करें",
    regenerateDiagram: "आरेख फिर से बनाएं",
    chatCompanion: "एआई अध्ययन साथी"
  },
  fr: {
    brandName: "Curricula.AI",
    dashboard: "Tableau de Bord",
    syllabus: "Programme",
    learningStats: "Statistiques d'Apprentissage",
    streak: "Série d'Apprentissage",
    activeDays: "Jours Actifs",
    avatar: "Choisir un Avatar",
    language: "Langue de l'Interface",
    logout: "Se Déconnecter",
    settings: "Paramètres",
    saveChanges: "Enregistrer",
    cancel: "Annuler",
    searchPlaceholder: "Rechercher des concepts, leçons, résumés...",
    backToDashboard: "Retour au Tableau de Bord",
    courseSyllabus: "Programme du Cours",
    aiTutor: "Tuteur IA",
    resumeLearning: "Reprendre l'Apprentissage",
    exportCourse: "Exporter le Cours",
    chapter: "Chapitre",
    lesson: "Leçon",
    startQuiz: "Démarrer le Quiz",
    suggestedQueries: "Suggestions de Requêtes",
    noCourses: "Aucun cours généré. Téléchargez un PDF ci-dessous pour commencer !",
    uploadPdf: "Télécharger un PDF",
    uploadSuccess: "Téléchargement réussi !",
    generatingCourse: "Génération du Cours...",
    createCourse: "Créer un Cours",
    yourCourses: "Vos Cours",
    studyStats: "Statistiques d'Étude",
    recentActivity: "Activité Récente",
    settingsTitle: "Paramètres & Préférences",
    profile: "Paramètres du Profil",
    security: "Sécurité & 2FA",
    password: "Paramètres de Mot de Passe",
    notifications: "Préférences de Notification",
    aiPreferences: "Préférences du Modèle IA",
    appearance: "Thème & Apparence",
    account: "Gestion du Compte",
    signIn: "Se Connecter",
    signUp: "S'inscrire",
    emailAddress: "Adresse E-mail",
    passwordLabel: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    firstName: "Prénom",
    lastName: "Nom",
    haveAccount: "Vous avez déjà un compte ?",
    noAccount: "Vous n'avez pas de compte ?",
    interactiveDiagrams: "Diagrammes Interactifs",
    visualMindMaps: "Cartes Mentales & Diagrammes IA",
    chapterTopic: "Sujet du Chapitre",
    visualLayout: "Type de Disposition Visuelle",
    mindmap: "Carte Mentale",
    conceptFlowchart: "Organigramme de Concepts",
    sequenceDiagram: "Diagramme de Séquence",
    classStructure: "Structure des Classes",
    erd: "Relation Entité (ERD)",
    exportSvg: "Exporter SVG",
    zoomControls: "Controles du Zoom",
    fitToScreen: "Ajuster à l'Écran",
    regenerateDiagram: "Régénérer le Diagramme",
    chatCompanion: "Compagnon d'Étude IA"
  },
  de: {
    brandName: "Curricula.AI",
    dashboard: "Dashboard",
    syllabus: "Lehrplan",
    learningStats: "Lernstatistiken",
    streak: "Lernserie",
    activeDays: "Aktive Tage",
    avatar: "Avatar Auswählen",
    language: "Oberflächensprache",
    logout: "Abmelden",
    settings: "Einstellungen",
    saveChanges: "Änderungen Speichern",
    cancel: "Abbrechen",
    searchPlaceholder: "Suche nach Konzepten, Lektionen, Zusammenfassungen...",
    backToDashboard: "Zurück zum Dashboard",
    courseSyllabus: "Kurslehrplan",
    aiTutor: "KI-Tutor",
    resumeLearning: "Lernen Fortsetzen",
    exportCourse: "Kurs Exportieren",
    chapter: "Kapitel",
    lesson: "Lektion",
    startQuiz: "Quiz Starten",
    suggestedQueries: "Empfohlene Fragen",
    noCourses: "Noch keine Kurse erstellt. Laden Sie unten eine PDF-Datei hoch, um zu beginnen!",
    uploadPdf: "PDF Hochladen",
    uploadSuccess: "Upload erfolgreich!",
    generatingCourse: "Kurs wird generiert...",
    createCourse: "Kurs Erstellen",
    yourCourses: "Ihre Kurse",
    studyStats: "Lernstatistiken",
    recentActivity: "Letzte Aktivitäten",
    settingsTitle: "Einstellungen & Präferenzen",
    profile: "Profileinstellungen",
    security: "Sicherheit & 2FA",
    password: "Passworteinstellungen",
    notifications: "Benachrichtigungseinstellungen",
    aiPreferences: "KI-Modelleinstellungen",
    appearance: "Thema & Aussehen",
    account: "Kontoverwaltung",
    signIn: "Anmelden",
    signUp: "Registrieren",
    emailAddress: "E-Mail-Adresse",
    passwordLabel: "Passwort",
    forgotPassword: "Passwort vergessen?",
    firstName: "Vorname",
    lastName: "Nachname",
    haveAccount: "Bereits ein Konto?",
    noAccount: "Noch kein Konto?",
    interactiveDiagrams: "Interaktive Diagramme",
    visualMindMaps: "KI-Visuelle Mindmaps & Diagramme",
    chapterTopic: "Kapitelthema",
    visualLayout: "Visueller Layouttyp",
    mindmap: "Mindmap",
    conceptFlowchart: "Konzept-Ablaufdiagramm",
    sequenceDiagram: "Sequenzdiagramm",
    classStructure: "Klassenstruktur",
    erd: "Entity-Relationship (ERD)",
    exportSvg: "SVG Exportieren",
    zoomControls: "Zoom-Steuerung",
    fitToScreen: "An Bildschirm Anpassen",
    regenerateDiagram: "Diagramm Regenerieren",
    chatCompanion: "KI-Lernpartner"
  },
  ja: {
    brandName: "Curricula.AI",
    dashboard: "ダッシュボード",
    syllabus: "シラバス",
    learningStats: "学習統計",
    streak: "学習ストリーク",
    activeDays: "アクティブ日数",
    avatar: "アバターを選択",
    language: "インターフェース言語",
    logout: "ログアウト",
    settings: "設定",
    saveChanges: "変更を保存",
    cancel: "キャンセル",
    searchPlaceholder: "概念、レッスン、概要を検索します...",
    backToDashboard: "ダッシュボードに戻る",
    courseSyllabus: "コースのシラバス",
    aiTutor: "AIチューター",
    resumeLearning: "学習を再開する",
    exportCourse: "コースをエクスポート",
    chapter: "章",
    lesson: "レッスン",
    startQuiz: "クイズを開始",
    suggestedQueries: "推奨質問",
    noCourses: "コースはまだ生成されていません。開始するには以下からPDFをアップロードしてください！",
    uploadPdf: "PDFをアップロード",
    uploadSuccess: "アップロード成功！",
    generatingCourse: "コースを生成中...",
    createCourse: "コース作成",
    yourCourses: "あなたのコース",
    studyStats: "学習状況",
    recentActivity: "最近のアクティビティ",
    settingsTitle: "設定と基本設定",
    profile: "プロフィール設定",
    security: "セキュリティと2FA",
    password: "パスワード設定",
    notifications: "通知設定",
    aiPreferences: "AIモデル設定",
    appearance: "テーマと外観",
    account: "アカウント管理",
    signIn: "サインイン",
    signUp: "新規登録",
    emailAddress: "メールアドレス",
    passwordLabel: "パスワード",
    forgotPassword: "パスワードをお忘れですか？",
    firstName: "名",
    lastName: "姓",
    haveAccount: "すでにアカウントをお持ちですか？",
    noAccount: "アカウントをお持ちでないですか？",
    interactiveDiagrams: "対話型図面",
    visualMindMaps: "AIビジュアルマインドマップと図",
    chapterTopic: "章のトピック",
    visualLayout: "ビジュアルレイアウトタイプ",
    mindmap: "マインドマップ",
    conceptFlowchart: "概念フローチャート",
    sequenceDiagram: "シーケンス図",
    classStructure: "クラス構造",
    erd: "実体関連図 (ERD)",
    exportSvg: "SVGをエクスポート",
    zoomControls: "ズームコントロール",
    fitToScreen: "画面に合わせる",
    regenerateDiagram: "図の再生成",
    chatCompanion: "AI学習コンパニオン"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('language') as Language;
      if (stored && ['en', 'hi', 'es', 'fr', 'de', 'ja'].includes(stored)) {
        setLanguageState(stored);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return dictionaries[language]?.[key] || dictionaries['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
